import Realm from "realm";
import {
  UserSchema,
  BairroSchema,
  CidadeSchema,
  CondicaoSchema,
  FormulaSchema,
  Grupo1Schema,
  Grupo2ExcecaoSchema,
  Grupo2Schema,
  Grupo3Schema,
  GrupoExcecaoSchema,
  ItemExcecaoAutoSchema,
  ItemSchema,
  PessoaItemSchema,
  PessoaSchema,
  PromocaoItemSchema,
  TabelaSchema,
  UnidadeSchema,
  FilialSchema,
} from "./schemas";

export const getRealm = async () =>
  await Realm.open({
    path: "publiDataBase",
    schema: [
      UserSchema,
      BairroSchema,
      CidadeSchema,
      CondicaoSchema,
      FormulaSchema,
      FilialSchema,
      Grupo1Schema,
      Grupo2ExcecaoSchema,
      Grupo2Schema,
      Grupo3Schema,
      GrupoExcecaoSchema,
      ItemExcecaoAutoSchema,
      ItemSchema,
      PessoaItemSchema,
      PessoaSchema,
      PromocaoItemSchema,
      TabelaSchema,
      UnidadeSchema,
    ],
  });
