import { ObjectSchema } from "realm";

export const FilialSchema: ObjectSchema = {
  name: "FilialSchema",

  properties: {
    Handle: "int",
    HandleFilial: "int",
    HandleTrade: "int",
    HandleGrupoFilial: "int",
    Nome: "string",
    Razao: "string",
    Fone: "string",
    CnpjCpf: "string",
    NomeSite: "string",
    BackgroudColor: "string",
    FontColor: "string",
    TitleColor: "string",
    Titulo01: "string",
    Texto01: "string",
    Titulo02: "string",
    Texto02: "string",
    Logo: "string",
    ValorPedidoMinimo: "double",
    Endereco: "string",
    Numero: "string",
    Complemento: "string",
    Bairro: "string",
    Cep: "string",
    Cidade: "string",
    Estado: "string",
    NumeroWhatsAppPedido: "string",
    PrevisaoEntregaMin: "int",
    PrevisaoRetiraMin: "int",
    TipoFrete: "string",
    MensagemTaxaEntrega: "string",
    TaxaEntrega: "double",
    Titulo01Cardapio: "string",
    Texto01Cardapio: "string",
    Titulo02Cardapio: "string",
    Texto02Cardapio: "string",
    ApiKeyHere: "string",
    ConfigPrecoPizza: "string",
    PossuiIntegracao: "bool",
    TipoAtendimento: "int",
    Plataforma: "int",
    HandleTabela: "int",
    Preco: "double",
    PossuiValidacaoEndereco: "bool",
    ImagemPadraoPizza: "string",
    ObrigatorioEnviarPedidoPeloWhatsApp: "bool",
    HandleRamoAtividade: "int",
    PathRelPedidoSowPublisoft: "string",
    EmailHost: "string",
    EmailUsuario: "string",
    EmailSenha: "string",
    EmailPorta: "string",
    Timeout: "int",
    EmailAtivarSsl: "bool",
    MensagemPedidoEmail: "string",
    HandleFranquia: "int",
    LimiteRetirada: "int",
    IntervaloAgendamento: "int",
    UtilizaHorarioAgendamento: "bool",
    GatewayPagamento: "string",
    ChavePublica: "string",
    ChaveSecreta: "string",
    MostarExcecaoPedidoVenda: "bool",
    LayoutTelaItensSowPublisoft: "string",
    PermiteDigitacaoPreco: "bool",
    QuantidadeInteira: "bool",
    DiasPrevisaoEntrega: "int",
    QtdAparelhosLiberadosPubliVendas: "int",
    ChaveApps: "string",
  },

  primaryKey: "Handle",
};
