export const PessoaSchema = {
  name: "PessoaSchema",

  properties: {
    Handle: "long",
    HandleFilial: "long",
    HandleTrade: "int",
    Plataforma: "int",
    Codigo: "int",
    Nome: "string",
    Fantasia: "string",
    CnpjCpf: "string",
    Endereco: "string",
    Numero: "int",
    Complemento: "string",
    Proximidade: "varchar",
    Bairro: "string",
    Cep: "string",
    Cidade: "string",
    Email: "string",
    Telefone: "string",
    Observacao: "string",
    Tipo: "varchar",
    HandleTabela: "long",
    Uf: "varchar",
    HandleUsuario: "long",
    Insc: "varchar",
    Bloqueado: "bool",
    ObservacaoPessoa: "string",
    HandleCondicao: "long",
  },

  primaryKey: "Handle",
};
